/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (ApeEscapeRecomp)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* confirmed: Jumptable on a0 (18 cases). Case 4/14 start busy=2; case 8/15 poll then busy=1. */
#define PSX_FN_CardMenuDispatch 0x80010000u
#define func_80010000 CardMenuDispatch  /* alias */

/* confirmed: Sets B4E30=1, installs LibCardHandlerBusy1 via LibCardInstallHandler. Master LOAD path. */
#define PSX_FN_LibCardStartBusy1 0x80020B60u
#define func_80020B60 LibCardStartBusy1  /* alias */

/* confirmed: IntRP/callback for busy-code 1 ops (file list / bu00). */
#define PSX_FN_LibCardHandlerBusy1 0x80020BC8u
#define func_80020BC8 LibCardHandlerBusy1  /* alias */

/* confirmed: Sets B4E30=2, installs LibCardHandlerBusy2. Tip LOAD Checking path; wedges if nest incomplete. */
#define PSX_FN_LibCardStartBusy2 0x80020EE4u
#define func_80020EE4 LibCardStartBusy2  /* alias */

/* confirmed: Busy2 FSM; jumptable 0x800A3960. Valid phases 6/17/26/27/46; tip hang saw phase 0x1F (default return 0). */
#define PSX_FN_LibCardHandlerBusy2 0x80020F4Cu
#define func_80020F4C LibCardHandlerBusy2  /* alias */

/* confirmed: a0=0 consume B4E38 completion; a0!=0 poll. Spins at 0x80021F14 on B4E38. */
#define PSX_FN_LibCardWaitOrPoll 0x80021EC8u
#define func_80021EC8 LibCardWaitOrPoll  /* alias */

/* confirmed: SIO IntRP: pops A6C10 nest; latches B4E38 only on idle 0xFFFFFFFF. */
#define PSX_FN_LibCardIntRP 0x800226C8u
#define func_800226C8 LibCardIntRP  /* alias */

/* confirmed: Copies B4E30→B4E20, clears busy, invokes completion callback. */
#define PSX_FN_LibCardPublishResult 0x80022700u
#define func_80022700 LibCardPublishResult  /* alias */

/* confirmed: Installs B4ED0 handler pointer for current libcard op. */
#define PSX_FN_LibCardInstallHandler 0x80022830u
#define func_80022830 LibCardInstallHandler  /* alias */

/* confirmed: EvCB CALLBACK for HwCARD/IOE — stores 1 at B4F00. Phase27 waits on this. */
#define PSX_FN_LibCardHwCardFlagIoe 0x80022930u
#define func_80022930 LibCardHwCardFlagIoe  /* alias */

/* confirmed: EvCB CALLBACK for SwCARD/IOE — stores 1 at B4F10. Tip hang has this set. */
#define PSX_FN_LibCardSwCardFlagIoe 0x80022980u
#define func_80022980 LibCardSwCardFlagIoe  /* alias */
